'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17626
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ImgBrick5.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;/Item&gt;
        '''&lt;/roblox&gt;.
        '''</summary>
        Friend ReadOnly Property ExportXML_E() As String
            Get
                Return ResourceManager.GetString("ExportXML_E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;Item class=&quot;Part&quot; referent=&quot;RBX12&quot;&gt;
        '''&lt;Properties&gt;
        '''&lt;bool name=&quot;Anchored&quot;&gt;true&lt;/bool&gt;
        '''&lt;token name=&quot;BottomSurface&quot;&gt;0&lt;/token&gt;
        '''&lt;Color3 name=&quot;Color&quot;&gt;
        '''&lt;R&gt;$r&lt;/R&gt;
        '''&lt;G&gt;$g&lt;/G&gt;
        '''&lt;B&gt;$b&lt;/B&gt;
        '''&lt;/Color3&gt;
        '''&lt;CoordinateFrame name=&quot;CFrame&quot;&gt;
        '''&lt;X&gt;$x&lt;/X&gt;
        '''&lt;Y&gt;$y&lt;/Y&gt;
        '''&lt;Z&gt;$z&lt;/Z&gt;
        '''&lt;R00&gt;1&lt;/R00&gt;
        '''&lt;R01&gt;0&lt;/R01&gt;
        '''&lt;R02&gt;0&lt;/R02&gt;
        '''&lt;R10&gt;0&lt;/R10&gt;
        '''&lt;R11&gt;1&lt;/R11&gt;
        '''&lt;R12&gt;0&lt;/R12&gt;
        '''&lt;R20&gt;0&lt;/R20&gt;
        '''&lt;R21&gt;0&lt;/R21&gt;
        '''&lt;R22&gt;1&lt;/R22&gt;
        '''&lt;/CoordinateFrame&gt;
        '''&lt;token name=&quot;FormFactor&quot;&gt;0&lt;/token&gt;
        '''&lt;string name=&quot;Name&quot;&gt;Pixel&lt;/string&gt;
        '''&lt;token name=&quot;TopSurface&quot;&gt;0&lt;/token&gt;
        '''&lt;float name=&quot;Transparency [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ExportXML_Part() As String
            Get
                Return ResourceManager.GetString("ExportXML_Part", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;roblox xmlns:xmime=&quot;http://www.w3.org/2005/05/xmlmime&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:noNamespaceSchemaLocation=&quot;http://www.roblox.com/roblox.xsd&quot; version=&quot;4&quot;&gt;
        '''&lt;External&gt;null&lt;/External&gt;
        '''&lt;External&gt;nil&lt;/External&gt;
        '''&lt;Item class=&quot;Model&quot; referent=&quot;RBX0&quot;&gt;
        '''&lt;Properties&gt;
        '''&lt;CoordinateFrame name=&quot;ModelInPrimary&quot;&gt;
        '''&lt;X&gt;0&lt;/X&gt;
        '''&lt;Y&gt;0&lt;/Y&gt;
        '''&lt;Z&gt;0&lt;/Z&gt;
        '''&lt;R00&gt;1&lt;/R00&gt;
        '''&lt;R01&gt;0&lt;/R01&gt;
        '''&lt;R02&gt;0&lt;/R02&gt;
        '''&lt;R10&gt;0&lt;/R10&gt;
        '''&lt;R11&gt;1&lt;/R11&gt;
        '''&lt;R12&gt;0&lt;/R12&gt;
        '''&lt;R20&gt;0&lt;/R20&gt;
        '''&lt;R21&gt;0&lt;/R21&gt;
        '''&lt;R22&gt;1&lt;/R22&gt;
        '''&lt;/CoordinateFrame&gt;
        '''&lt;string name=&quot;Name&quot;&gt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ExportXML_S() As String
            Get
                Return ResourceManager.GetString("ExportXML_S", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ImgBrick (III) Help
        '''Developed by Dade L. (Havemeat)
        '''http://TheRKommunity.WordPress.com/
        '''-------------------
        '''
        '''****************************************************
        '''				OPENING AN IMAGE
        '''****************************************************
        '''
        '''1-Open up ImgBrick.
        '''2-Press the &apos;Open&apos; button in the upper-left hand corner of the window.
        '''3-Choose an image file (.png, .jpeg, .jpg, .bmp, .gif, or .ico)
        '''4-The image you use choose must be smaller than or equal to 480 x 270.
        '''5-If the image is too large then the [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Help() As String
            Get
                Return ResourceManager.GetString("Help", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
